//
//  UIColor+JCAdditions.m
//
//  Generated by Zeplin on 6/30/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

#import "UIColor+JCAdditions.h"

@implementation UIColor (JCAdditions)

+ (UIColor *)jc_tomatoColor {
	return [UIColor colorWithRed:239.0f / 255.0f green:102.0f / 255.0f blue:35.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_blackColor {
	return [UIColor colorWithWhite:0.0 alpha:1.0f];
}

+ (UIColor *)jc_cloudyBlueColor {
	return [UIColor colorWithRed:211.0f / 255.0f green:218.0f / 255.0f blue:227.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_peachColor {
	return [UIColor colorWithRed:247.0f / 255.0f green:185.0f / 255.0f blue:126.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_vermillionColor {
	return [UIColor colorWithRed:244.0f / 255.0f green:61.0f / 255.0f blue:16.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_tangerineColor {
	return [UIColor colorWithRed:255.0f / 255.0f green:144.0f / 255.0f blue:0.0 alpha:1.0f];
}

+ (UIColor *)jc_brickOrange40Color {
	return [UIColor colorWithRed:194.0f / 255.0f green:48.0f / 255.0f blue:7.0f / 255.0f alpha:0.4f];
}

+ (UIColor *)jc_slateGreyColor {
	return [UIColor colorWithRed:88.0f / 255.0f green:89.0f / 255.0f blue:91.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_brickOrangeColor {
	return [UIColor colorWithRed:194.0f / 255.0f green:48.0f / 255.0f blue:8.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_blackTwoColor {
	return [UIColor colorWithWhite:45.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_orangeRedColor {
	return [UIColor colorWithRed:255.0f / 255.0f green:99.0f / 255.0f blue:44.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_fadedOrangeColor {
	return [UIColor colorWithRed:244.0f / 255.0f green:167.0f / 255.0f blue:105.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_brownishGreyColor {
	return [UIColor colorWithWhite:91.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_deepOrangeColor {
	return [UIColor colorWithRed:219.0f / 255.0f green:58.0f / 255.0f blue:1.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_blueyGreyColor {
	return [UIColor colorWithRed:173.0f / 255.0f green:182.0f / 255.0f blue:194.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_beigeColor {
	return [UIColor colorWithRed:236.0f / 255.0f green:193.0f / 255.0f blue:156.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_reddishOrangeColor {
	return [UIColor colorWithRed:245.0f / 255.0f green:90.0f / 255.0f blue:35.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_reddishBrownColor {
	return [UIColor colorWithRed:130.0f / 255.0f green:37.0f / 255.0f blue:9.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_reddishOrangeTwoColor {
	return [UIColor colorWithRed:241.0f / 255.0f green:90.0f / 255.0f blue:30.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_tomatoTwoColor {
	return [UIColor colorWithRed:240.0f / 255.0f green:98.0f / 255.0f blue:33.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_reddishOrangeThreeColor {
	return [UIColor colorWithRed:241.0f / 255.0f green:78.0f / 255.0f blue:24.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_rustyRedColor {
	return [UIColor colorWithRed:175.0f / 255.0f green:56.0f / 255.0f blue:21.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_brightOrangeColor {
	return [UIColor colorWithRed:255.0f / 255.0f green:110.0f / 255.0f blue:0.0 alpha:1.0f];
}

+ (UIColor *)jc_pumpkinColor {
	return [UIColor colorWithRed:234.0f / 255.0f green:112.0f / 255.0f blue:0.0 alpha:1.0f];
}

+ (UIColor *)jc_pumpkinOrangeColor {
	return [UIColor colorWithRed:255.0f / 255.0f green:122.0f / 255.0f blue:0.0 alpha:1.0f];
}

+ (UIColor *)jc_lightBlueColor {
	return [UIColor colorWithRed:140.0f / 255.0f green:210.0f / 255.0f blue:255.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_squashColor {
	return [UIColor colorWithRed:245.0f / 255.0f green:166.0f / 255.0f blue:35.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_lavenderPinkColor {
	return [UIColor colorWithRed:213.0f / 255.0f green:117.0f / 255.0f blue:205.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_purplishPinkColor {
	return [UIColor colorWithRed:203.0f / 255.0f green:104.0f / 255.0f blue:173.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_uglyPurpleColor {
	return [UIColor colorWithRed:179.0f / 255.0f green:73.0f / 255.0f blue:147.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_butterscotchColor {
	return [UIColor colorWithRed:255.0f / 255.0f green:185.0f / 255.0f blue:70.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_silverColor {
	return [UIColor colorWithRed:224.0f / 255.0f green:226.0f / 255.0f blue:229.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_darkSkyBlueColor {
	return [UIColor colorWithRed:70.0f / 255.0f green:161.0f / 255.0f blue:220.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_windowsBlueColor {
	return [UIColor colorWithRed:56.0f / 255.0f green:138.0f / 255.0f blue:191.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_darkSkyBlueTwoColor {
	return [UIColor colorWithRed:100.0f / 255.0f green:173.0f / 255.0f blue:220.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_babyBlueColor {
	return [UIColor colorWithRed:158.0f / 255.0f green:217.0f / 255.0f blue:255.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_tomatoRedColor {
	return [UIColor colorWithRed:213.0f / 255.0f green:46.0f / 255.0f blue:0.0 alpha:1.0f];
}

+ (UIColor *)jc_sunflowerYellowColor {
	return [UIColor colorWithRed:255.0f / 255.0f green:211.0f / 255.0f blue:0.0 alpha:1.0f];
}

+ (UIColor *)jc_coolGreyColor {
	return [UIColor colorWithRed:150.0f / 255.0f green:157.0f / 255.0f blue:166.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_device1Color {
	return [UIColor colorWithRed:255.0f / 255.0f green:195.0f / 255.0f blue:24.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_device2Color {
	return [UIColor colorWithRed:161.0f / 255.0f green:216.0f / 255.0f blue:67.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_device4Color {
	return [UIColor colorWithRed:0.0 green:190.0f / 255.0f blue:254.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_device3Color {
	return [UIColor colorWithRed:85.0f / 255.0f green:205.0f / 255.0f blue:200.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_device5Color {
	return [UIColor colorWithRed:245.0f / 255.0f green:63.0f / 255.0f blue:64.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_device6Color {
	return [UIColor colorWithRed:255.0f / 255.0f green:129.0f / 255.0f blue:56.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_device7Color {
	return [UIColor colorWithRed:250.0f / 255.0f green:78.0f / 255.0f blue:165.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_device12Color {
	return [UIColor colorWithRed:136.0f / 255.0f green:113.0f / 255.0f blue:231.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_device11Color {
	return [UIColor colorWithRed:155.0f / 255.0f green:158.0f / 255.0f blue:185.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_device10Color {
	return [UIColor colorWithRed:184.0f / 255.0f green:166.0f / 255.0f blue:137.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_coolGreyTwoColor {
	return [UIColor colorWithRed:151.0f / 255.0f green:157.0f / 255.0f blue:166.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_device9Color {
	return [UIColor colorWithRed:158.0f / 255.0f green:120.0f / 255.0f blue:120.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_seafoamBlueTwoColor {
	return [UIColor colorWithRed:91.0f / 255.0f green:205.0f / 255.0f blue:200.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_dustyOrangeColor {
	return [UIColor colorWithRed:230.0f / 255.0f green:101.0f / 255.0f blue:47.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_coolGrey60Color {
	return [UIColor colorWithRed:171.0f / 255.0f green:179.0f / 255.0f blue:189.0f / 255.0f alpha:0.6f];
}

+ (UIColor *)jc_coolGrey70Color {
	return [UIColor colorWithRed:171.0f / 255.0f green:179.0f / 255.0f blue:189.0f / 255.0f alpha:0.7f];
}

+ (UIColor *)jc_blackThreeColor {
	return [UIColor colorWithWhite:3.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_black50Color {
	return [UIColor colorWithWhite:0.0 alpha:0.5f];
}

+ (UIColor *)jc_coolGrey50Color {
	return [UIColor colorWithRed:171.0f / 255.0f green:179.0f / 255.0f blue:189.0f / 255.0f alpha:0.5f];
}

+ (UIColor *)jc_white10Color {
	return [UIColor colorWithWhite:255.0f / 255.0f alpha:0.1f];
}

+ (UIColor *)jc_silverTwoColor {
	return [UIColor colorWithRed:223.0f / 255.0f green:225.0f / 255.0f blue:228.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_silverThreeColor {
	return [UIColor colorWithRed:201.0f / 255.0f green:205.0f / 255.0f blue:210.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_tomato50Color {
	return [UIColor colorWithRed:239.0f / 255.0f green:102.0f / 255.0f blue:34.0f / 255.0f alpha:0.5f];
}

+ (UIColor *)jc_chestnutColor {
	return [UIColor colorWithRed:95.0f / 255.0f green:22.0f / 255.0f blue:0.0 alpha:1.0f];
}

+ (UIColor *)jc_tealishColor {
	return [UIColor colorWithRed:68.0f / 255.0f green:205.0f / 255.0f blue:201.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_coolGreyThreeColor {
	return [UIColor colorWithRed:178.0f / 255.0f green:182.0f / 255.0f blue:187.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_tomato40Color {
	return [UIColor colorWithRed:239.0f / 255.0f green:102.0f / 255.0f blue:34.0f / 255.0f alpha:0.4f];
}

+ (UIColor *)jc_device8Color {
	return [UIColor colorWithRed:0.0 green:126.0f / 255.0f blue:224.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_coolGreyTwo30Color {
	return [UIColor colorWithRed:151.0f / 255.0f green:157.0f / 255.0f blue:166.0f / 255.0f alpha:0.3f];
}

+ (UIColor *)jc_slateGreyTwoColor {
	return [UIColor colorWithRed:92.0f / 255.0f green:99.0f / 255.0f blue:108.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_slateGreyThreeColor {
	return [UIColor colorWithRed:93.0f / 255.0f green:99.0f / 255.0f blue:108.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_softBlueColor {
	return [UIColor colorWithRed:81.0f / 255.0f green:134.0f / 255.0f blue:241.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_blackFourColor {
	return [UIColor colorWithWhite:34.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_fadedBlueColor {
	return [UIColor colorWithRed:105.0f / 255.0f green:169.0f / 255.0f blue:192.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_fadedBlueTwoColor {
	return [UIColor colorWithRed:95.0f / 255.0f green:169.0f / 255.0f blue:193.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_fadedBlueThreeColor {
	return [UIColor colorWithRed:91.0f / 255.0f green:166.0f / 255.0f blue:193.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_coolBlueColor {
	return [UIColor colorWithRed:77.0f / 255.0f green:166.0f / 255.0f blue:194.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_warmGreyColor {
	return [UIColor colorWithWhite:151.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_white50Color {
	return [UIColor colorWithWhite:255.0f / 255.0f alpha:0.5f];
}

+ (UIColor *)jc_slateGrey50Color {
	return [UIColor colorWithRed:92.0f / 255.0f green:98.0f / 255.0f blue:108.0f / 255.0f alpha:0.5f];
}

+ (UIColor *)jc_charcoalGreyColor {
	return [UIColor colorWithRed:61.0f / 255.0f green:61.0f / 255.0f blue:66.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_darkColor {
	return [UIColor colorWithRed:28.0f / 255.0f green:29.0f / 255.0f blue:34.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_warmGreyTwoColor {
	return [UIColor colorWithWhite:153.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_whiteColor {
	return [UIColor colorWithWhite:255.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_slateGreyFourColor {
	return [UIColor colorWithRed:101.0f / 255.0f green:108.0f / 255.0f blue:117.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_whiteTwoColor {
	return [UIColor colorWithWhite:219.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_greyishBrownColor {
	return [UIColor colorWithWhite:72.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)jc_black25Color {
	return [UIColor colorWithWhite:0.0 alpha:0.25f];
}

@end
