//
//  UIColor+JCAdditions.h
//
//  Generated by Zeplin on 6/30/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

#import <UIKit/UIKit.h>

@interface UIColor (JCAdditions)

+ (UIColor *)jc_tomatoColor;
+ (UIColor *)jc_blackColor;
+ (UIColor *)jc_cloudyBlueColor;
+ (UIColor *)jc_peachColor;
+ (UIColor *)jc_vermillionColor;
+ (UIColor *)jc_tangerineColor;
+ (UIColor *)jc_brickOrange40Color;
+ (UIColor *)jc_slateGreyColor;
+ (UIColor *)jc_brickOrangeColor;
+ (UIColor *)jc_blackTwoColor;
+ (UIColor *)jc_orangeRedColor;
+ (UIColor *)jc_fadedOrangeColor;
+ (UIColor *)jc_brownishGreyColor;
+ (UIColor *)jc_deepOrangeColor;
+ (UIColor *)jc_blueyGreyColor;
+ (UIColor *)jc_beigeColor;
+ (UIColor *)jc_reddishOrangeColor;
+ (UIColor *)jc_reddishBrownColor;
+ (UIColor *)jc_reddishOrangeTwoColor;
+ (UIColor *)jc_tomatoTwoColor;
+ (UIColor *)jc_reddishOrangeThreeColor;
+ (UIColor *)jc_rustyRedColor;
+ (UIColor *)jc_brightOrangeColor;
+ (UIColor *)jc_pumpkinColor;
+ (UIColor *)jc_pumpkinOrangeColor;
+ (UIColor *)jc_lightBlueColor;
+ (UIColor *)jc_squashColor;
+ (UIColor *)jc_lavenderPinkColor;
+ (UIColor *)jc_purplishPinkColor;
+ (UIColor *)jc_uglyPurpleColor;
+ (UIColor *)jc_butterscotchColor;
+ (UIColor *)jc_silverColor;
+ (UIColor *)jc_darkSkyBlueColor;
+ (UIColor *)jc_windowsBlueColor;
+ (UIColor *)jc_darkSkyBlueTwoColor;
+ (UIColor *)jc_babyBlueColor;
+ (UIColor *)jc_tomatoRedColor;
+ (UIColor *)jc_sunflowerYellowColor;
+ (UIColor *)jc_coolGreyColor;
+ (UIColor *)jc_device1Color;
+ (UIColor *)jc_device2Color;
+ (UIColor *)jc_device4Color;
+ (UIColor *)jc_device3Color;
+ (UIColor *)jc_device5Color;
+ (UIColor *)jc_device6Color;
+ (UIColor *)jc_device7Color;
+ (UIColor *)jc_device12Color;
+ (UIColor *)jc_device11Color;
+ (UIColor *)jc_device10Color;
+ (UIColor *)jc_coolGreyTwoColor;
+ (UIColor *)jc_device9Color;
+ (UIColor *)jc_seafoamBlueTwoColor;
+ (UIColor *)jc_dustyOrangeColor;
+ (UIColor *)jc_coolGrey60Color;
+ (UIColor *)jc_coolGrey70Color;
+ (UIColor *)jc_blackThreeColor;
+ (UIColor *)jc_black50Color;
+ (UIColor *)jc_coolGrey50Color;
+ (UIColor *)jc_white10Color;
+ (UIColor *)jc_silverTwoColor;
+ (UIColor *)jc_silverThreeColor;
+ (UIColor *)jc_tomato50Color;
+ (UIColor *)jc_chestnutColor;
+ (UIColor *)jc_tealishColor;
+ (UIColor *)jc_coolGreyThreeColor;
+ (UIColor *)jc_tomato40Color;
+ (UIColor *)jc_device8Color;
+ (UIColor *)jc_coolGreyTwo30Color;
+ (UIColor *)jc_slateGreyTwoColor;
+ (UIColor *)jc_slateGreyThreeColor;
+ (UIColor *)jc_softBlueColor;
+ (UIColor *)jc_blackFourColor;
+ (UIColor *)jc_fadedBlueColor;
+ (UIColor *)jc_fadedBlueTwoColor;
+ (UIColor *)jc_fadedBlueThreeColor;
+ (UIColor *)jc_coolBlueColor;
+ (UIColor *)jc_warmGreyColor;
+ (UIColor *)jc_white50Color;
+ (UIColor *)jc_slateGrey50Color;
+ (UIColor *)jc_charcoalGreyColor;
+ (UIColor *)jc_darkColor;
+ (UIColor *)jc_warmGreyTwoColor;
+ (UIColor *)jc_whiteColor;
+ (UIColor *)jc_slateGreyFourColor;
+ (UIColor *)jc_whiteTwoColor;
+ (UIColor *)jc_greyishBrownColor;
+ (UIColor *)jc_black25Color;

@end
