//
//  UIFont+JCAdditions.h
//
//  Generated by Zeplin on 6/30/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

#import <UIKit/UIKit.h>

@interface UIFont (JCAdditions)

+ (UIFont *)jc_textStyleFont;
+ (UIFont *)jc_textStyle10Font;
+ (UIFont *)jc_textStyle7Font;
+ (UIFont *)jc_textStyle32Font;
+ (UIFont *)jc_textStyle16Font;
+ (UIFont *)jc_textStyle41Font;
+ (UIFont *)jc_textStyle6Font;
+ (UIFont *)jc_textStyle5Font;
+ (UIFont *)jc_textStyle43Font;
+ (UIFont *)jc_textStyle11Font;
+ (UIFont *)jc_textStyle26Font;
+ (UIFont *)jc_textStyle23Font;
+ (UIFont *)jc_textStyle3Font;
+ (UIFont *)jc_textStyle9Font;
+ (UIFont *)jc_textStyle33Font;
+ (UIFont *)jc_textStyle24Font;
+ (UIFont *)jc_textStyle37Font;
+ (UIFont *)jc_textStyle2Font;
+ (UIFont *)jc_textStyle46Font;
+ (UIFont *)jc_textStyle21Font;
+ (UIFont *)jc_textStyle27Font;
+ (UIFont *)jc_textStyle30Font;
+ (UIFont *)jc_textStyle38Font;
+ (UIFont *)jc_textStyle17Font;
+ (UIFont *)jc_textStyle42Font;
+ (UIFont *)jc_textStyle14Font;
+ (UIFont *)jc_textStyle31Font;
+ (UIFont *)jc_textStyle13Font;
+ (UIFont *)jc_textStyle22Font;
+ (UIFont *)jc_textStyle28Font;
+ (UIFont *)jc_textStyle44Font;
+ (UIFont *)jc_textStyle45Font;
+ (UIFont *)jc_textStyle34Font;
+ (UIFont *)jc_textStyle40Font;
+ (UIFont *)jc_textStyle39Font;
+ (UIFont *)jc_textStyle18Font;
+ (UIFont *)jc_textStyle8Font;
+ (UIFont *)jc_textStyle19Font;
+ (UIFont *)jc_textStyle29Font;
+ (UIFont *)jc_textStyle15Font;
+ (UIFont *)jc_textStyle12Font;
+ (UIFont *)jc_textStyle36Font;
+ (UIFont *)jc_textStyle4Font;
+ (UIFont *)jc_textStyle25Font;
+ (UIFont *)jc_textStyle35Font;
+ (UIFont *)jc_textStyle20Font;

@end
