//
//  UIFont+JCAdditions.m
//
//  Generated by Zeplin on 6/30/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

#import "UIFont+JCAdditions.h"

@implementation UIFont (JCAdditions)

+ (UIFont *)jc_textStyleFont {
	return [UIFont fontWithName:@"HelveticaNeue-Bold" size:25.0f];
}

+ (UIFont *)jc_textStyle10Font {
	return [UIFont fontWithName:@"HelveticaNeue" size:21.0f];
}

+ (UIFont *)jc_textStyle7Font {
	return [UIFont fontWithName:@"Helvetica-Bold" size:20.0f];
}

+ (UIFont *)jc_textStyle32Font {
	return [UIFont fontWithName:@"HelveticaNeue-Medium" size:20.0f];
}

+ (UIFont *)jc_textStyle16Font {
	return [UIFont fontWithName:@"HelveticaNeue-Medium" size:20.0f];
}

+ (UIFont *)jc_textStyle41Font {
	return [UIFont fontWithName:@"HelveticaNeue" size:20.0f];
}

+ (UIFont *)jc_textStyle6Font {
	return [UIFont fontWithName:@"HelveticaNeue-Light" size:20.0f];
}

+ (UIFont *)jc_textStyle5Font {
	return [UIFont fontWithName:@".HelveticaNeueDeskInterface-MediumP4" size:18.0f];
}

+ (UIFont *)jc_textStyle43Font {
	return [UIFont fontWithName:@"HelveticaNeue-Medium" size:18.0f];
}

+ (UIFont *)jc_textStyle11Font {
	return [UIFont fontWithName:@"HelveticaNeue-Medium" size:18.0f];
}

+ (UIFont *)jc_textStyle26Font {
	return [UIFont fontWithName:@"HelveticaNeue-Light" size:18.0f];
}

+ (UIFont *)jc_textStyle23Font {
	return [UIFont fontWithName:@"HelveticaNeue-Medium" size:17.0f];
}

+ (UIFont *)jc_textStyle3Font {
	return [UIFont fontWithName:@"HelveticaNeue-Medium" size:17.0f];
}

+ (UIFont *)jc_textStyle9Font {
	return [UIFont fontWithName:@"HelveticaNeue-Medium" size:17.0f];
}

+ (UIFont *)jc_textStyle33Font {
	return [UIFont fontWithName:@"HelveticaNeue-Medium" size:17.0f];
}

+ (UIFont *)jc_textStyle24Font {
	return [UIFont fontWithName:@"HelveticaNeue-Medium" size:17.0f];
}

+ (UIFont *)jc_textStyle37Font {
	return [UIFont fontWithName:@"HelveticaNeue" size:17.0f];
}

+ (UIFont *)jc_textStyle2Font {
	return [UIFont fontWithName:@"Helvetica" size:16.0f];
}

+ (UIFont *)jc_textStyle46Font {
	return [UIFont fontWithName:@"Helvetica" size:16.0f];
}

+ (UIFont *)jc_textStyle21Font {
	return [UIFont fontWithName:@"HelveticaNeue-Light" size:16.0f];
}

+ (UIFont *)jc_textStyle27Font {
	return [UIFont fontWithName:@"HelveticaNeue-Light" size:16.0f];
}

+ (UIFont *)jc_textStyle30Font {
	return [UIFont fontWithName:@"HelveticaNeue-Light" size:16.0f];
}

+ (UIFont *)jc_textStyle38Font {
	return [UIFont fontWithName:@"HelveticaNeue-Medium" size:15.0f];
}

+ (UIFont *)jc_textStyle17Font {
	return [UIFont fontWithName:@"HelveticaNeue-Medium" size:15.0f];
}

+ (UIFont *)jc_textStyle42Font {
	return [UIFont fontWithName:@"HelveticaNeue-Medium" size:15.0f];
}

+ (UIFont *)jc_textStyle14Font {
	return [UIFont fontWithName:@"HelveticaNeue-Medium" size:15.0f];
}

+ (UIFont *)jc_textStyle31Font {
	return [UIFont fontWithName:@"HelveticaNeue" size:15.0f];
}

+ (UIFont *)jc_textStyle13Font {
	return [UIFont fontWithName:@"HelveticaNeue" size:15.0f];
}

+ (UIFont *)jc_textStyle22Font {
	return [UIFont fontWithName:@"HelveticaNeue-Light" size:15.0f];
}

+ (UIFont *)jc_textStyle28Font {
	return [UIFont fontWithName:@"HelveticaNeue-Light" size:15.0f];
}

+ (UIFont *)jc_textStyle44Font {
	return [UIFont fontWithName:@"HelveticaNeue" size:14.57f];
}

+ (UIFont *)jc_textStyle45Font {
	return [UIFont fontWithName:@"HelveticaNeue-Medium" size:14.0f];
}

+ (UIFont *)jc_textStyle34Font {
	return [UIFont fontWithName:@"HelveticaNeue-Medium" size:14.0f];
}

+ (UIFont *)jc_textStyle40Font {
	return [UIFont fontWithName:@".HelveticaNeueDeskInterface-Regular" size:14.0f];
}

+ (UIFont *)jc_textStyle39Font {
	return [UIFont fontWithName:@"Helvetica" size:14.0f];
}

+ (UIFont *)jc_textStyle18Font {
	return [UIFont fontWithName:@"HelveticaNeue" size:14.0f];
}

+ (UIFont *)jc_textStyle8Font {
	return [UIFont fontWithName:@"HelveticaNeue" size:14.0f];
}

+ (UIFont *)jc_textStyle19Font {
	return [UIFont fontWithName:@"HelveticaNeue-Light" size:14.0f];
}

+ (UIFont *)jc_textStyle29Font {
	return [UIFont fontWithName:@"Helvetica" size:13.03f];
}

+ (UIFont *)jc_textStyle15Font {
	return [UIFont fontWithName:@"Helvetica" size:12.0f];
}

+ (UIFont *)jc_textStyle12Font {
	return [UIFont fontWithName:@"HelveticaNeue" size:12.0f];
}

+ (UIFont *)jc_textStyle36Font {
	return [UIFont fontWithName:@"HelveticaNeue" size:12.0f];
}

+ (UIFont *)jc_textStyle4Font {
	return [UIFont fontWithName:@"HelveticaNeue" size:12.0f];
}

+ (UIFont *)jc_textStyle25Font {
	return [UIFont fontWithName:@"HelveticaNeue" size:12.0f];
}

+ (UIFont *)jc_textStyle35Font {
	return [UIFont fontWithName:@"HelveticaNeue" size:10.0f];
}

+ (UIFont *)jc_textStyle20Font {
	return [UIFont fontWithName:@"HelveticaNeue-Light" size:10.0f];
}

@end
